"""Analyst Dashboard — single-coin institutional read rendered from a
structured analysis file produced by the locked framework
(framework/analyst_framework_v1.md).

This is a scaffold: it proves the separate-page architecture (the Market
Scanner in app.py is untouched). The schema + renderer land next.
"""
from __future__ import annotations

import streamlit as st

st.set_page_config(page_title="Analyst Dashboard", page_icon="📊", layout="wide")

# Surface page navigation as a horizontal in-page list (top-left); hide sidebar nav.
st.markdown(
    "<style>[data-testid='stSidebarNav']{display:none;}"
    "[data-testid='stHeader']{display:none;}"
    ".block-container{padding-top:1.6rem;}"
    ".st-key-topnav{flex-direction:row!important;gap:1.1rem;align-items:center;}"
    ".st-key-topnav [data-testid='stElementContainer']{width:auto!important;}"
    ".st-key-topnav [data-testid='stMarkdownContainer'] p{width:auto!important;"
    "overflow:visible!important;text-overflow:clip!important;white-space:nowrap;}</style>",
    unsafe_allow_html=True,
)
navc = st.columns([1, 2.5])[0]
with navc:
    _nav = st.container(key="topnav")
    _nav.page_link("app.py", label="Market Scanner")
    _nav.page_link("pages/1_Analyst_Dashboard.py", label="Analyst Dashboard")

st.title("📊 Analyst Dashboard")

st.caption(
    "Institutional-style single-coin read, generated by the locked analyst "
    "framework. Type a ticker and Scan to load its latest analysis."
)

# Placeholder header controls (wiring comes with the renderer step).
csel, cbtn = st.columns([3, 1], vertical_alignment="bottom")
csel.text_input("Ticker", placeholder="e.g. HYPEUSDT", label_visibility="collapsed")
cbtn.button("Scan", use_container_width=True)

st.divider()
st.info(
    "Scaffold in place. Next: define the analysis schema and build the "
    "dashboard renderer, validated against the HYPE analysis.",
    icon="🚧",
)
