"""Analyst Dashboard — single-coin institutional read rendered from a
structured analysis file (analyses/<SYMBOL>.json) produced by the locked
framework (framework/analyst_framework_v1.md).

The Market Scanner in app.py is untouched; this page is fully isolated.
"""
from __future__ import annotations

import streamlit as st

import dashboard

st.set_page_config(page_title="Analyst Dashboard", page_icon="📊", layout="wide")

# Surface page navigation as a horizontal in-page list (top-left); hide sidebar nav.
st.markdown(
    "<style>[data-testid='stSidebarNav']{display:none;}"
    "[data-testid='stHeader']{display:none;}"
    ".block-container{padding-top:1.6rem;}"
    ".st-key-topnav{flex-direction:row!important;gap:1.1rem;align-items:center;}"
    ".st-key-topnav [data-testid='stElementContainer']{width:auto!important;}"
    ".st-key-topnav [data-testid='stMarkdownContainer'] p{width:auto!important;"
    "overflow:visible!important;text-overflow:clip!important;white-space:nowrap;}</style>",
    unsafe_allow_html=True,
)
navc = st.columns([1, 2.5])[0]
with navc:
    _nav = st.container(key="topnav")
    _nav.page_link("app.py", label="Market Scanner")
    _nav.page_link("pages/1_Analyst_Dashboard.py", label="Analyst Dashboard")

st.caption(
    "Institutional-style single-coin read, generated by the locked analyst "
    "framework. Type a ticker and Scan to load its latest analysis."
)

# Ticker input + Scan (75% / 25%).
csel, cbtn = st.columns([3, 1], vertical_alignment="bottom")
typed = csel.text_input("Ticker", placeholder="e.g. HYPEUSDT", label_visibility="collapsed")
if cbtn.button("Scan", use_container_width=True) and typed.strip():
    st.session_state["dash_symbol"] = typed.strip().upper()
    st.rerun()

# Default to the HYPE reference analysis so the dashboard isn't empty on first open.
symbol = st.session_state.get("dash_symbol", "HYPEUSDT")
data = dashboard.load_analysis(symbol)

st.divider()
if data:
    st.caption(
        f"Showing **{data.get('symbol', symbol)}** · analysis time "
        f"{data.get('meta', {}).get('analysis_time', '—')} · framework "
        f"{data.get('framework_version', 'v1')}"
    )
    dashboard.render(data)
else:
    st.warning(
        f"No analysis on file for **{symbol}**. Ask Claude in chat to run the "
        f"framework on {symbol}, then Scan again.",
        icon="📭",
    )
