[theme]
base = "dark"
primaryColor = "#4c8dff"
backgroundColor = "#061326"
secondaryBackgroundColor = "#15181f"
textColor = "#e6e8eb"
font = "sans serif"

[server]
headless = false
enableStaticServing = true

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
